Visual Studio/AspnCrudDapper/AspnCrudDapper/Entities/Produto.cs
using System.ComponentModel.DataAnnotations;

namespace AspnCrudDapper.Entities
{
    public class Produto
    {
        [Key]
        [Display(Name = "Id")]
        public int ProdutoId { get; set; }

        [Required]
        [Display(Name = "Nome do Produto")]
        [StringLength(25, ErrorMessage = "O nome deve ter entre 1 até 25 caracteres.")]
        public string Nome { get; set; }

        [Required]
        [Display(Name = "Stock")]
        [Range(1, int.MaxValue, ErrorMessage = "Valor deve ser maior ou igual a 1")]
        public int Estoque { get; set; }

        [Required]
        [Display(Name = "Preço")]
        public double Preco { get; set; }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Produto/Add.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using AspnCrudDapper.Repository;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages.Produto
{
    public class AddModel : PageModel
    {
        private readonly IProdutoRepository _produtoRepository;

        #region Public Properties
        [BindProperty]
        public Entities.Produto Produto { get; set; }

        [TempData]
        public string Message { get; set; }
        #endregion

        public AddModel(IProdutoRepository produtoRepository) =>
            _produtoRepository = produtoRepository;

        #region Public Methods
        public void OnGet() => Page();

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                var count = _produtoRepository.Add(Produto);

                if (count > 0)
                {
                    Message = "Novo Produto incluído com sucesso!";

                    return RedirectToPage("/Produto/Index");
                }
            }

            return Page();
        }
        #endregion
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Produto/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using AspnCrudDapper.Repository;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages.Produto
{
    public class EditModel : PageModel
    {
        private readonly IProdutoRepository _produtoRepository;

        [BindProperty]
        public Entities.Produto Produto { get; set; }

        public EditModel(IProdutoRepository produtoRepository) =>
            _produtoRepository = produtoRepository;

        public void OnGet(int id) =>
            Produto = _produtoRepository.Get(id);

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                var count = _produtoRepository.Edit(Produto);

                if (count > 0)
                {
                    return RedirectToPage("/Produto/Index");
                }
            }

            return Page();
        }
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Produto/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using AspnCrudDapper.Repository;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AspnCrudDapper.Pages.Produto
{
    public class IndexModel : PageModel
    {
        private readonly IProdutoRepository _produtoRepository;

        #region Public Properties
        [BindProperty]
        public IEnumerable<Entities.Produto> ListaProdutos { get; set; }

        [TempData]
        public string Message { get; set; }
        #endregion

        public IndexModel(IProdutoRepository produtoRepository) =>
            _produtoRepository = produtoRepository;

        #region Public Methods
        public void OnGet() => ListaProdutos = _produtoRepository.GetProdutos();        

        public IActionResult OnPostDelete(int id)
        {
            if (id > 0)
            {
                var count = _produtoRepository.Delete(id);

                if (count > 0)
                {
                    Message = "Produto Apagado com sucesso!";
                    return RedirectToPage("/Produto/Index");
                }
            }

            return Page();
        }
        #endregion
    }
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Produto/Add.cshtml
@page
@model AspnCrudDapper.Pages.Produto.AddModel
@{
    ViewData["Title"] = "Adicionar Novo Produto";
}

<div>
    <div>
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title"><strong>Novo Produto</strong></h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4 item_img">
                        <img src="~/images/addProduto.jpg" class="img-responsive">
                    </div>
                    <div class="col-md-8 item_content">
                        <form method="post" id="ProdutoForm">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="panel">
                                            <div class="panel-body">
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="Produto.Nome" style="font-weight:bold;"></label>
                                                    <input type='text' class='form-control' asp-for="Produto.Nome" />
                                                    <span class="alert-danger" asp-validation-for="Produto.Nome"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="Produto.Estoque" style="font-weight:bold;"></label>
                                                    <input type='text' class='form-control' asp-for="Produto.Estoque" />
                                                    <span class="alert-danger" asp-validation-for="Produto.Estoque"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="Produto.Preco" style="font-weight:bold;"></label>
                                                    <input asp-for="Produto.Preco" type="hidden" />
                                                    <input type="number" class="form-control" id="Produto_Preco_Number" min="0" step="0.01" />
                                                    <span class="alert-danger" asp-validation-for="Produto.Preco"></span>
                                                </div>
                                                <div class="text-center col-md-12" style="margin-top:35px;">
                                                    <button class="btn btn-primary btn-sx" type="submit">
                                                        <i class="glyphicon glyphicon-plus"></i> Adicionar Produto
                                                    </button>
                                                    <hr id="hrId" />
                                                    <a class="btn btn-success btn-sx" asp-page="/Produto/Index">
                                                        <i class="glyphicon glyphicon-backward"></i> Lista de Produtos
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#Produto_Preco_Number').val($('#Produto_Preco').val().replace(',', '.'));

            $('#ProdutoForm').submit(function () {
                $('#Produto_Preco').val($('#Produto_Preco_Number').val().replace('.', ','));
            })
        });
    </script>
}

@section Css{
    <style>
        #hrId {
            border-top: none;
        }
    </style>
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Produto/Edit.cshtml
@page
@model AspnCrudDapper.Pages.Produto.EditModel
@{
    ViewData["Title"] = "Editar Produto";
}
<div>
    <div>
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title"><strong>Editar Produto</strong></h3>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-4 item_img">
                        <img src="~/images/editProduto.jpg" class="img-responsive">
                    </div>
                    <div class="col-md-8 item_content">
                        <form id="ProdutoForm" method="post">
                            <div class="container">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="panel">
                                            <div class="panel-body">
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <input asp-for="Produto.ProdutoId" type="hidden" />
                                                    <label asp-for="Produto.Nome" style="font-weight:bold;"></label>
                                                    <input type='text' class='form-control' asp-for="Produto.Nome" />
                                                    <span class="alert-danger" asp-validation-for="Produto.Nome"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="Produto.Estoque" style="font-weight:bold;"></label>
                                                    <input type='number' class='form-control' asp-for="Produto.Estoque" />
                                                    <span class="alert-danger" asp-validation-for="Produto.Estoque"></span>
                                                </div>
                                                <div class="col-md-12" style="margin-top:15px;">
                                                    <label asp-for="Produto.Preco" style="font-weight:bold;"></label>
                                                    <input asp-for="Produto.Preco" type="hidden" />
                                                    <input type="number" class="form-control" id="Produto_Preco_Number" min="0" step="0.01" />
                                                    <span class="alert-danger" asp-validation-for="Produto.Preco"></span>
                                                </div>
                                                <div class="text-center col-md-12" style="margin-top:35px;">
                                                    <button class="btn btn-primary btn-sx" type="submit">
                                                        <i class="glyphicon glyphicon-edit"></i> Editar Produto
                                                    </button>
                                                    <a class="btn btn-success btn-sx" asp-page="/Produto/Index">
                                                        <i class="glyphicon glyphicon-backward"></i> Lista De Produtos
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#Produto_Preco_Number').val($('#Produto_Preco').val().replace(',', '.'));

            $('#ProdutoForm').submit(function () {
                $('#Produto_Preco').val($('#Produto_Preco_Number').val().replace('.', ','));
            })
        });
    </script>
}

Visual Studio/AspnCrudDapper/AspnCrudDapper/Pages/Produto/Index.cshtml
@page
@model AspnCrudDapper.Pages.Produto.IndexModel
@{
    ViewData["Title"] = "Produtos";
}

<div class="container">
    <div class="mail-box">
        <aside class="lg-side">
            <div class="inbox-head">
                <h3>Produtos</h3>
            </div>
            <a class="btn btn-primary btn-sx pull-left" style="margin-top: 20px; margin-bottom: 20px;" asp-page="/Produto/Add">
                <i class="glyphicon glyphicon-plus"></i> Adicionar Novo Produto
            </a>
            <br />

            @{
                if (!string.IsNullOrEmpty(Model.Message))
                {
                    <div class="alert alert-success" id="success-alert" style="margin-top: 40px;">
                        <button type="button" class="close" data-dismiss="alert">X</button>
                        <strong>@Model.Message!</strong>
                    </div>
                }
            }

            <div class="inbox-body" style="margin-top: 20px;">
                <div class="mail-option">
                    <table class="table table-inbox table-hover" style="border: 2px solid black;">
                        <thead>
                            <tr class="unread">
                                <th class="col-sm-2 view-message dont-show">Id</th>
                                <th class="col-sm-3 view-message">Nome</th>
                                <th class="col-sm-2">Stock</th>
                                <th class="col-sm-2 view-message text-left">Preço</th>
                                <th class="col-sm-1"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ListaProdutos)
                            {
                                <tr>
                                    <td onclick="macFunction()" class="view-message dont-show"><h5>@item.ProdutoId</h5></td>
                                    <td onclick="macFunction()" class="view-message"><h5>@item.Nome</h5></td>
                                    <td onclick="macFunction()" class="view-message"><h5>@item.Estoque</h5></td>
                                    <td onclick="macFunction()" class="view-message"><h5>@string.Format("{0:C}", item.Preco)</h5></td>
                                    <td>
                                        <form method="post">
                                            <span class="btn-group pull-right" style="margin-top: 5px;">
                                                <a class="btn btn-warning btn-xs" asp-page="/Produto/Edit" asp-route-id="@item.ProdutoId" style="background-color: blueviolet; height: 29px; margin-top: -1px;"><i class="glyphicon glyphicon-edit"></i></a>

                                                <button type="submit" class="btn btn-danger btn-xs" asp-page-handler="Delete" asp-route-id="@item.ProdutoId" style="height: 27px; margin-top: 0px;" onclick="return confirm('Deseja realmente apagar este produto?')">
                                                    <i class="glyphicon glyphicon-remove"></i>
                                                </button>
                                            </span>
                                        </form>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </aside>
    </div>
</div>

@section Scripts {
    <script>
        function macFunction() {
            $('#item_view').modal();
        };

        $(document).ready(function () {
            $('#success-alert').hide();

            $('#success-alert').fadeTo(2000, 500).slideUp(500, function () {
                $('#success-alert').slideUp(500);
            });
        });
    </script>
}